To get Robolectric working with Android Studio: - Need to install the plugins, follow the instructions, from https://github.com/robolectric/deckard-gradle . I could not figure out how to get it working as a module, so instead moved my app module code to the top-level. Frustrating. - Needed to add a dependency from the test onto the actual app code, so that changes trigger proper rebuilds. This is done here: http://blog.blundell-apps.com/how-to-run-robolectric-junit-tests-in-android-studio/ - We needed to downgrade to SDK version 18, to work with robolectric (which doesn’t yet support any newer versions) http://blog.blundell-apps.com/android-gradle-app-with-robolectric-junit-tests/. I decided to change my build environment to 18 to verify I’m testing what I’m building, though alternately one can build in 19 and test in 18, if one were okay with the version skew. - Needed my own RobolectricTestRunner, that specifies the androidmanifest.xml and res directory we wish to use (and optionally, assets, if necessary). this is one example of that: http://blog.blundell-apps.com/android-gradle-app-with-robolectric-junit-tests/ - Have to keep updating the classpath for our run targets. Perhaps I could simplify this if I made a gradle target which represented what I wanted, and that in turn used the right classpaths? In particular, the classpath needs to have a directory added to it, to point at the generated java tests classfiles... https://groups.google.com/forum/#!topic/robolectric/xsOpEwtdTi4 - had to add testCompile with the junit stuff (instead of just androidTestCompile), so that the java test files we need are available outside the android test framework: https://github.com/JakeWharton/gradle-android-test-plugin/issues/35 - had to manually add android.jar to the classpath, for use by the tests, to avoid java.lang.NoClassDefFoundError: android/R. in theory, robolectric might be a better fit for these android classes, though haven’t tested that one fully yet…we already have manual class overrides anyway. http://stackoverflow.com/questions/16950104/java-lang-classnotfoundexception-android-r  though maybe if we stick a dependency inside our testCompile on android.jar somehow, that would help? - Similarly, it appears that multiple resources overlay each other, and get overlayed into the build/intermediates/res/ directory. This is the res directory that has both GooglePlayServices (and their version numbers) as well as my app showing up in the same res/ directory, so we need to have our robolectric test runner point to that instead. http://tools.android.com/tech-docs/new-build-system/resource-merging - We need to install JDK 1.7, since GoogleApiClient actually requires JDK 1.7 (51) and the entire Android Studio is running on the basic Mac JDK 1.6 (50), which means even with Robolectric, it wasn’t able to provide an execution environment capable of running GMS. https://code.google.com/p/android/issues/detail?id=75080&thanks=75080&ts=1408547102 and https://github.com/robolectric/robolectric/issues/1186 and https://github.com/robolectric/robolectric/issues/1075 - Needed to disable parse (which wants to check the network connection privileges, in a way i suspect is not handled by robolectric’s mocking). Did it in a TestApplication. - Needed to disable google analytics (which has crazy stack frames, and other google-obfuscated crap), to avoid a NullPointerException. Did it in a TestApplication. http://stackoverflow.com/questions/19731798/robolectric-and-google-analytics-error-on-tests and http://robolectric.blogspot.com/2013/04/the-test-lifecycle-in-20.html